import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding ports data...')

  // Ports data from UN/LOCODE - Expanded with major international ports
  const portsData = [
    // Colombia Ports
    {
      name: 'Acacías',
      country: 'Colombia',
      unloc: 'COAAS',
      code: 'AAS',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Acandí',
      country: 'Colombia',
      unloc: 'COACD',
      code: 'ACD',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Agrado',
      country: 'Colombia',
      unloc: 'COAGD',
      code: 'AGD',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Aguachica',
      country: 'Colombia',
      unloc: 'COAGC',
      code: 'AGC',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Aguaclara',
      country: 'Colombia',
      unloc: 'COACL',
      code: 'ACL',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Aguadas',
      country: 'Colombia',
      unloc: 'COAGU',
      code: 'AGU',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Aguas Blancas',
      country: 'Colombia',
      unloc: 'COABL',
      code: 'ABL',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Amalfi',
      country: 'Colombia',
      unloc: 'COAFI',
      code: 'AFI',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Andalucía',
      country: 'Colombia',
      unloc: 'COAND',
      code: 'AND',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Andes',
      country: 'Colombia',
      unloc: 'COADN',
      code: 'ADN',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Antioquia',
      country: 'Colombia',
      unloc: 'COAQA',
      code: 'AQA',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Apartadó',
      country: 'Colombia',
      unloc: 'COAPO',
      code: 'APO',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Apartadó',
      country: 'Colombia',
      unloc: 'COLAP',
      code: 'LAP',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Apiay',
      country: 'Colombia',
      unloc: 'COAPI',
      code: 'API',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Aracataca',
      country: 'Colombia',
      unloc: 'COARA',
      code: 'ARA',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Araracuara',
      country: 'Colombia',
      unloc: 'COACR',
      code: 'ACR',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Arauca',
      country: 'Colombia',
      unloc: 'COAUC',
      code: 'AUC',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Arauquita',
      country: 'Colombia',
      unloc: 'COARQ',
      code: 'ARQ',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Arboletas',
      country: 'Colombia',
      unloc: 'COARO',
      code: 'ARO',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Arenal',
      country: 'Colombia',
      unloc: 'COARE',
      code: 'ARE',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Arica',
      country: 'Colombia',
      unloc: 'COACM',
      code: 'ACM',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Ariguaní',
      country: 'Colombia',
      unloc: 'COARI',
      code: 'ARI',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Arjona',
      country: 'Colombia',
      unloc: 'COARJ',
      code: 'ARJ',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Armenia',
      country: 'Colombia',
      unloc: 'COAXM',
      code: 'AXM',
      latitude: null,
      longitude: null,
    },
    {
      name: 'Barranquilla',
      country: 'Colombia',
      unloc: 'COBAQ',
      code: 'BAQ',
      latitude: 10.968,
      longitude: -74.781,
    },
    {
      name: 'Bogotá',
      country: 'Colombia',
      unloc: 'COBOG',
      code: 'BOG',
      latitude: 4.6,  // 04°36'N = 4.6°N
      longitude: -74.083,  // 74°05'W = -74.083°
    },
    {
      name: 'Cartagena',
      country: 'Colombia',
      unloc: 'COCTG',
      code: 'CTG',
      latitude: 10.391,
      longitude: -75.479,
    },
    {
      name: 'Medellín',
      country: 'Colombia',
      unloc: 'COMDE',
      code: 'MDE',
      latitude: 6.283,  // 06°17'N = 6.283°N
      longitude: -75.533,  // 75°32'W = -75.533°
    },
    {
      name: 'Cali',
      country: 'Colombia',
      unloc: 'COCLO',
      code: 'CLO',
      latitude: 3.437,
      longitude: -76.522,
    },
    {
      name: 'Santa Marta',
      country: 'Colombia',
      unloc: 'COSMR',
      code: 'SMR',
      latitude: 11.242,
      longitude: -74.203,
    },
    {
      name: 'Bucaramanga',
      country: 'Colombia',
      unloc: 'COBGA',
      code: 'BGA',
      latitude: 7.125,
      longitude: -73.119,
    },
    // Major International Ports
    {
      name: 'Shanghai',
      country: 'China',
      unloc: 'CNSHA',
      code: 'SHA',
      latitude: 31.230,
      longitude: 121.473,
    },
    {
      name: 'Singapore',
      country: 'Singapore',
      unloc: 'SGSIN',
      code: 'SIN',
      latitude: 1.352,
      longitude: 103.819,
    },
    {
      name: 'Rotterdam',
      country: 'Netherlands',
      unloc: 'NLRTM',
      code: 'RTM',
      latitude: 51.924,
      longitude: 4.477,
    },
    {
      name: 'Antwerp',
      country: 'Belgium',
      unloc: 'BEANR',
      code: 'ANR',
      latitude: 51.219,
      longitude: 4.402,
    },
    {
      name: 'Hamburg',
      country: 'Germany',
      unloc: 'DEHAM',
      code: 'HAM',
      latitude: 53.551,
      longitude: 9.993,
    },
    {
      name: 'Los Angeles',
      country: 'United States',
      unloc: 'USLAX',
      code: 'LAX',
      latitude: 33.942,
      longitude: -118.408,
    },
    {
      name: 'Long Beach',
      country: 'United States',
      unloc: 'USLGB',
      code: 'LGB',
      latitude: 33.768,
      longitude: -118.192,
    },
    {
      name: 'New York',
      country: 'United States',
      unloc: 'USNYC',
      code: 'NYC',
      latitude: 40.712,
      longitude: -74.006,
    },
    {
      name: 'Hong Kong',
      country: 'China',
      unloc: 'HKHKG',
      code: 'HKG',
      latitude: 22.319,
      longitude: 114.169,
    },
    {
      name: 'Dubai',
      country: 'United Arab Emirates',
      unloc: 'AEDXB',
      code: 'DXB',
      latitude: 25.204,
      longitude: 55.270,
    },
    {
      name: 'Busan',
      country: 'South Korea',
      unloc: 'KRPUS',
      code: 'PUS',
      latitude: 35.179,
      longitude: 129.075,
    },
    {
      name: 'Tokyo',
      country: 'Japan',
      unloc: 'JPTYO',
      code: 'TYO',
      latitude: 35.676,
      longitude: 139.650,
    },
    {
      name: 'Yokohama',
      country: 'Japan',
      unloc: 'JPYOK',
      code: 'YOK',
      latitude: 35.443,
      longitude: 139.638,
    },
    {
      name: 'Kaohsiung',
      country: 'Taiwan',
      unloc: 'TWKHH',
      code: 'KHH',
      latitude: 22.627,
      longitude: 120.301,
    },
    {
      name: 'Qingdao',
      country: 'China',
      unloc: 'CNTAO',
      code: 'TAO',
      latitude: 36.067,
      longitude: 120.382,
    },
    {
      name: 'Ningbo',
      country: 'China',
      unloc: 'CNNGB',
      code: 'NGB',
      latitude: 29.868,
      longitude: 121.544,
    },
    {
      name: 'Guangzhou',
      country: 'China',
      unloc: 'CNCAN',
      code: 'CAN',
      latitude: 23.129,
      longitude: 113.264,
    },
    {
      name: 'Tianjin',
      country: 'China',
      unloc: 'CNTSN',
      code: 'TSN',
      latitude: 39.084,
      longitude: 117.201,
    },
    {
      name: 'Felixstowe',
      country: 'United Kingdom',
      unloc: 'GBFXT',
      code: 'FXT',
      latitude: 51.963,
      longitude: 1.341,
    },
    {
      name: 'Southampton',
      country: 'United Kingdom',
      unloc: 'GBSOU',
      code: 'SOU',
      latitude: 50.909,
      longitude: -1.404,
    },
    {
      name: 'Marseille',
      country: 'France',
      unloc: 'FRMRS',
      code: 'MRS',
      latitude: 43.296,
      longitude: 5.369,
    },
    {
      name: 'Le Havre',
      country: 'France',
      unloc: 'FRLEH',
      code: 'LEH',
      latitude: 49.487,
      longitude: 0.107,
    },
    {
      name: 'Algeciras',
      country: 'Spain',
      unloc: 'ESALG',
      code: 'ALG',
      latitude: 36.140,
      longitude: -5.445,
    },
    {
      name: 'Valencia',
      country: 'Spain',
      unloc: 'ESVLC',
      code: 'VLC',
      latitude: 39.469,
      longitude: -0.376,
    },
    {
      name: 'Barcelona',
      country: 'Spain',
      unloc: 'ESBCN',
      code: 'BCN',
      latitude: 41.385,
      longitude: 2.173,
    },
    {
      name: 'Genoa',
      country: 'Italy',
      unloc: 'ITGOA',
      code: 'GOA',
      latitude: 44.405,
      longitude: 8.946,
    },
    {
      name: 'Venice',
      country: 'Italy',
      unloc: 'ITVCE',
      code: 'VCE',
      latitude: 45.440,
      longitude: 12.315,
    },
    {
      name: 'Piraeus',
      country: 'Greece',
      unloc: 'GRPIR',
      code: 'PIR',
      latitude: 37.942,
      longitude: 23.646,
    },
    {
      name: 'Istanbul',
      country: 'Turkey',
      unloc: 'TRIST',
      code: 'IST',
      latitude: 41.008,
      longitude: 28.978,
    },
    {
      name: 'Alexandria',
      country: 'Egypt',
      unloc: 'EGALY',
      code: 'ALY',
      latitude: 31.200,
      longitude: 29.918,
    },
    {
      name: 'Jeddah',
      country: 'Saudi Arabia',
      unloc: 'SAJED',
      code: 'JED',
      latitude: 21.485,
      longitude: 39.192,
    },
    {
      name: 'Mumbai',
      country: 'India',
      unloc: 'INBOM',
      code: 'BOM',
      latitude: 19.076,
      longitude: 72.877,
    },
    {
      name: 'Chennai',
      country: 'India',
      unloc: 'INMAA',
      code: 'MAA',
      latitude: 13.082,
      longitude: 80.270,
    },
    {
      name: 'Colombo',
      country: 'Sri Lanka',
      unloc: 'LKCMB',
      code: 'CMB',
      latitude: 6.927,
      longitude: 79.861,
    },
    {
      name: 'Port Klang',
      country: 'Malaysia',
      unloc: 'MYKUL',
      code: 'KUL',
      latitude: 3.045,
      longitude: 101.418,
    },
    {
      name: 'Tanjung Priok',
      country: 'Indonesia',
      unloc: 'IDJKT',
      code: 'JKT',
      latitude: -6.208,
      longitude: 106.845,
    },
    {
      name: 'Sydney',
      country: 'Australia',
      unloc: 'AUSYD',
      code: 'SYD',
      latitude: -33.868,
      longitude: 151.209,
    },
    {
      name: 'Melbourne',
      country: 'Australia',
      unloc: 'AUMEL',
      code: 'MEL',
      latitude: -37.813,
      longitude: 144.963,
    },
    {
      name: 'Auckland',
      country: 'New Zealand',
      unloc: 'NZAKL',
      code: 'AKL',
      latitude: -36.848,
      longitude: 174.763,
    },
    {
      name: 'Manzanillo',
      country: 'Mexico',
      unloc: 'MXZLO',
      code: 'ZLO',
      latitude: 19.053,
      longitude: -104.312,
    },
    {
      name: 'Veracruz',
      country: 'Mexico',
      unloc: 'MXVER',
      code: 'VER',
      latitude: 19.173,
      longitude: -96.134,
    },
    {
      name: 'Buenos Aires',
      country: 'Argentina',
      unloc: 'ARBUE',
      code: 'BUE',
      latitude: -34.603,
      longitude: -58.381,
    },
    {
      name: 'Santos',
      country: 'Brazil',
      unloc: 'BRSSZ',
      code: 'SSZ',
      latitude: -23.550,
      longitude: -46.633,
    },
    {
      name: 'Rio de Janeiro',
      country: 'Brazil',
      unloc: 'BRRIO',
      code: 'RIO',
      latitude: -22.906,
      longitude: -43.172,
    },
    {
      name: 'Valparaíso',
      country: 'Chile',
      unloc: 'CLVAP',
      code: 'VAP',
      latitude: -33.045,
      longitude: -71.619,
    },
    {
      name: 'Callao',
      country: 'Peru',
      unloc: 'PECLL',
      code: 'CLL',
      latitude: -12.056,
      longitude: -77.118,
    },
    {
      name: 'Guayaquil',
      country: 'Ecuador',
      unloc: 'ECGYE',
      code: 'GYE',
      latitude: -2.170,
      longitude: -79.921,
    },
  ]

  // Clear existing ports data (optional - comment out if you want to keep existing data)
  await prisma.port.deleteMany()
  console.log('Cleared existing ports data')

  // Insert new ports data
  for (const portData of portsData) {
    await prisma.port.create({
      data: portData,
    })
  }

  console.log(`Successfully seeded ${portsData.length} ports`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })